// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package komodor

import (
	"context"
	"reflect"

	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves an existing Komodor Kubernetes cluster integration by name
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := komodor.LookupKubernetes(ctx, &komodor.LookupKubernetesArgs{
//				ClusterName: "my-cluster",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupKubernetes(ctx *pulumi.Context, args *LookupKubernetesArgs, opts ...pulumi.InvokeOption) (*LookupKubernetesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupKubernetesResult
	err := ctx.Invoke("komodor:index/getKubernetes:getKubernetes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKubernetes.
type LookupKubernetesArgs struct {
	// The name of the cluster; must be unique to a Komodor account
	ClusterName string `pulumi:"clusterName"`
}

// A collection of values returned by getKubernetes.
type LookupKubernetesResult struct {
	// The name of the cluster; must be unique to a Komodor account
	ClusterName string `pulumi:"clusterName"`
	// The id and api key of the cluster integration
	Id string `pulumi:"id"`
}

func LookupKubernetesOutput(ctx *pulumi.Context, args LookupKubernetesOutputArgs, opts ...pulumi.InvokeOption) LookupKubernetesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupKubernetesResultOutput, error) {
			args := v.(LookupKubernetesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("komodor:index/getKubernetes:getKubernetes", args, LookupKubernetesResultOutput{}, options).(LookupKubernetesResultOutput), nil
		}).(LookupKubernetesResultOutput)
}

// A collection of arguments for invoking getKubernetes.
type LookupKubernetesOutputArgs struct {
	// The name of the cluster; must be unique to a Komodor account
	ClusterName pulumi.StringInput `pulumi:"clusterName"`
}

func (LookupKubernetesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKubernetesArgs)(nil)).Elem()
}

// A collection of values returned by getKubernetes.
type LookupKubernetesResultOutput struct{ *pulumi.OutputState }

func (LookupKubernetesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKubernetesResult)(nil)).Elem()
}

func (o LookupKubernetesResultOutput) ToLookupKubernetesResultOutput() LookupKubernetesResultOutput {
	return o
}

func (o LookupKubernetesResultOutput) ToLookupKubernetesResultOutputWithContext(ctx context.Context) LookupKubernetesResultOutput {
	return o
}

// The name of the cluster; must be unique to a Komodor account
func (o LookupKubernetesResultOutput) ClusterName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKubernetesResult) string { return v.ClusterName }).(pulumi.StringOutput)
}

// The id and api key of the cluster integration
func (o LookupKubernetesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKubernetesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKubernetesResultOutput{})
}
