// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package komodor

import (
	"context"
	"reflect"

	"errors"
	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a new **Komodor monitor** to observe, detect, and analyze failures across your infrastructure. This resource allows you to define the parameters for monitoring specific components in your Kubernetes clusters and other infrastructure.
//
// ***
//
// ## Example Usage
//
// ### Deployment Monitor
//
// ### Valid Configurations:
// - **Valid Sinks**: `slack`, `teams`, `webhook`
// - **Valid notifyOn Options**:
//   - `"Failure"`
//   - `"Successful"`
//   - `"All"`
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := komodor.NewMonitor(ctx, "example-deploy-monitor", &komodor.MonitorArgs{
//				Active: pulumi.Bool(true),
//				Sensors: pulumi.String(`[{
//	  "cluster": "kind-kind",
//	  "exclude": {
//	    "namespaces": ["komodor"]
//	  },
//	  "namespaces": ["default"]
//	}]
//
// `),
//
//				Sinks: pulumi.String(`{
//	  "slack": ["deployment-alerts"],
//	  "teams": ["Platform-Team"]
//	}
//
// `),
//
//				SinksOptions: pulumi.String("{\n  \"notifyOn\": [\"Failure\", \"Successful\"]\n}\n\n"),
//				Type:         pulumi.String("deploy"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ***
//
// ### Availability Monitor
//
// ### Valid Configurations:
// - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
// - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
// - **Valid Categories for variables.categories**:
//   - `"Creating/Initializing"`
//   - `"Scheduling"`
//   - `"Container Creation"`
//   - `"NonZeroExitCode"`
//   - `"Unhealthy - failed probes"`
//   - `"OOMKilled"`
//   - `"BackOff"`
//   - `"Infrastructure"`
//   - `"Image"`
//   - `"Volume/Secret/ConfigMap"`
//   - `"Pod Termination"`
//   - `"Completed"`
//   - `"Other"`
//
// - **Valid notifyOn Options**: `["*"]`
//   - `["*"]` (all categories)
//   - Or any one of the following:
//   - `"Creating/Initializing"`
//   - `"Scheduling"`
//   - `"Container Creation"`
//   - `"NonZeroExitCode"`
//   - `"Unhealthy - failed probes"`
//   - `"OOMKilled"`
//   - `"BackOff"`
//   - `"Infrastructure"`
//   - `"Image"`
//   - `"Volume/Secret/ConfigMap"`
//   - `"Pod Termination"`
//   - `"Completed"`
//   - `"Other"`
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := komodor.NewMonitor(ctx, "example-availability-monitor", &komodor.MonitorArgs{
//				Active: pulumi.Bool(true),
//				Sensors: pulumi.String(`[{
//	  "cluster": "kind-kind",
//	  "exclude": {
//	    "services": ["default/excluded-service"]
//	  },
//	  "services": ["default/important-service"],
//	  "condition": "and",
//	  "namespaces": ["default"]
//	}]
//
// `),
//
//				Sinks: pulumi.String(`{
//	  "slack": ["availability-alerts"],
//	  "teams": ["SRE-Team"]
//	}
//
// `),
//
//				SinksOptions: pulumi.String("{\n  \"notifyOn\": [\"*\"]\n}\n\n"),
//				Type:         pulumi.String("availability"),
//				Variables: pulumi.String(`{
//	  "categories": ["Creating/Initializing", "Unhealthy - failed probes"],
//	  "duration": 30,
//	  "minAvailable": "100%"
//	}
//
// `),
//
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ***
//
// ### Node Monitor
//
// ### Valid Configurations:
// - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
// - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
// - **Valid NodeCreationThreshold: Should be in the format of `"3m"` (3 minutes) or `"5s"` (5 seconds).
// - **Valid Variables**:
//   - `duration`: Required
//   - `nodeCreationThreshold`: Required
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := komodor.NewMonitor(ctx, "example-node-monitor", &komodor.MonitorArgs{
//				Active:  pulumi.Bool(true),
//				Sensors: pulumi.String("[{\n  \"cluster\": \"kind-kind\"\n}]\n\n"),
//				Sinks:   pulumi.String("{\n  \"slack\": [\"node-alerts\"]\n}\n\n"),
//				Type:    pulumi.String("node"),
//				Variables: pulumi.String(`{
//	  "duration": 60,
//	  "nodeCreationThreshold": "10m"
//	}
//
// `),
//
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ***
//
// ### Workflow Monitor
//
// ### Valid Configurations:
// - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
// - **Valid notifyOn Options**: None (not applicable for workflows)
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := komodor.NewMonitor(ctx, "example-workflow-monitor", &komodor.MonitorArgs{
//				Active: pulumi.Bool(true),
//				Sensors: pulumi.String(`[{
//	  "cluster": "kind-kind",
//	  "namespaces": ["workflow-namespace"]
//	}]
//
// `),
//
//				Sinks: pulumi.String(`{
//	  "slack": ["workflow-alerts"],
//	  "webhook": ["webhook-url"]
//	}
//
// `),
//
//				Type: pulumi.String("workflow"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ***
type Monitor struct {
	pulumi.CustomResourceState

	// : Indicates whether the monitor is enabled.
	Active pulumi.BoolOutput `pulumi:"active"`
	// : Default is `false`. Indicates whether the monitor has been marked for deletion.
	IsDeleted pulumi.BoolPtrOutput `pulumi:"isDeleted"`
	// : The name of the monitor. Defaults to an empty string if not provided.
	Name pulumi.StringOutput `pulumi:"name"`
	// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
	Sensors pulumi.StringOutput `pulumi:"sensors"`
	// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
	Sinks pulumi.StringPtrOutput `pulumi:"sinks"`
	// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
	SinksOptions pulumi.StringPtrOutput `pulumi:"sinksOptions"`
	// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
	Type pulumi.StringOutput `pulumi:"type"`
	// : Additional settings required for specific monitor types.
	Variables pulumi.StringPtrOutput `pulumi:"variables"`
}

// NewMonitor registers a new resource with the given unique name, arguments, and options.
func NewMonitor(ctx *pulumi.Context,
	name string, args *MonitorArgs, opts ...pulumi.ResourceOption) (*Monitor, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Active == nil {
		return nil, errors.New("invalid value for required argument 'Active'")
	}
	if args.Sensors == nil {
		return nil, errors.New("invalid value for required argument 'Sensors'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Monitor
	err := ctx.RegisterResource("komodor:index/monitor:Monitor", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMonitor gets an existing Monitor resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMonitor(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MonitorState, opts ...pulumi.ResourceOption) (*Monitor, error) {
	var resource Monitor
	err := ctx.ReadResource("komodor:index/monitor:Monitor", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Monitor resources.
type monitorState struct {
	// : Indicates whether the monitor is enabled.
	Active *bool `pulumi:"active"`
	// : Default is `false`. Indicates whether the monitor has been marked for deletion.
	IsDeleted *bool `pulumi:"isDeleted"`
	// : The name of the monitor. Defaults to an empty string if not provided.
	Name *string `pulumi:"name"`
	// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
	Sensors *string `pulumi:"sensors"`
	// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
	Sinks *string `pulumi:"sinks"`
	// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
	SinksOptions *string `pulumi:"sinksOptions"`
	// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
	Type *string `pulumi:"type"`
	// : Additional settings required for specific monitor types.
	Variables *string `pulumi:"variables"`
}

type MonitorState struct {
	// : Indicates whether the monitor is enabled.
	Active pulumi.BoolPtrInput
	// : Default is `false`. Indicates whether the monitor has been marked for deletion.
	IsDeleted pulumi.BoolPtrInput
	// : The name of the monitor. Defaults to an empty string if not provided.
	Name pulumi.StringPtrInput
	// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
	Sensors pulumi.StringPtrInput
	// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
	Sinks pulumi.StringPtrInput
	// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
	SinksOptions pulumi.StringPtrInput
	// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
	Type pulumi.StringPtrInput
	// : Additional settings required for specific monitor types.
	Variables pulumi.StringPtrInput
}

func (MonitorState) ElementType() reflect.Type {
	return reflect.TypeOf((*monitorState)(nil)).Elem()
}

type monitorArgs struct {
	// : Indicates whether the monitor is enabled.
	Active bool `pulumi:"active"`
	// : Default is `false`. Indicates whether the monitor has been marked for deletion.
	IsDeleted *bool `pulumi:"isDeleted"`
	// : The name of the monitor. Defaults to an empty string if not provided.
	Name *string `pulumi:"name"`
	// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
	Sensors string `pulumi:"sensors"`
	// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
	Sinks *string `pulumi:"sinks"`
	// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
	SinksOptions *string `pulumi:"sinksOptions"`
	// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
	Type string `pulumi:"type"`
	// : Additional settings required for specific monitor types.
	Variables *string `pulumi:"variables"`
}

// The set of arguments for constructing a Monitor resource.
type MonitorArgs struct {
	// : Indicates whether the monitor is enabled.
	Active pulumi.BoolInput
	// : Default is `false`. Indicates whether the monitor has been marked for deletion.
	IsDeleted pulumi.BoolPtrInput
	// : The name of the monitor. Defaults to an empty string if not provided.
	Name pulumi.StringPtrInput
	// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
	Sensors pulumi.StringInput
	// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
	Sinks pulumi.StringPtrInput
	// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
	SinksOptions pulumi.StringPtrInput
	// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
	Type pulumi.StringInput
	// : Additional settings required for specific monitor types.
	Variables pulumi.StringPtrInput
}

func (MonitorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*monitorArgs)(nil)).Elem()
}

type MonitorInput interface {
	pulumi.Input

	ToMonitorOutput() MonitorOutput
	ToMonitorOutputWithContext(ctx context.Context) MonitorOutput
}

func (*Monitor) ElementType() reflect.Type {
	return reflect.TypeOf((**Monitor)(nil)).Elem()
}

func (i *Monitor) ToMonitorOutput() MonitorOutput {
	return i.ToMonitorOutputWithContext(context.Background())
}

func (i *Monitor) ToMonitorOutputWithContext(ctx context.Context) MonitorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MonitorOutput)
}

// MonitorArrayInput is an input type that accepts MonitorArray and MonitorArrayOutput values.
// You can construct a concrete instance of `MonitorArrayInput` via:
//
//	MonitorArray{ MonitorArgs{...} }
type MonitorArrayInput interface {
	pulumi.Input

	ToMonitorArrayOutput() MonitorArrayOutput
	ToMonitorArrayOutputWithContext(context.Context) MonitorArrayOutput
}

type MonitorArray []MonitorInput

func (MonitorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Monitor)(nil)).Elem()
}

func (i MonitorArray) ToMonitorArrayOutput() MonitorArrayOutput {
	return i.ToMonitorArrayOutputWithContext(context.Background())
}

func (i MonitorArray) ToMonitorArrayOutputWithContext(ctx context.Context) MonitorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MonitorArrayOutput)
}

// MonitorMapInput is an input type that accepts MonitorMap and MonitorMapOutput values.
// You can construct a concrete instance of `MonitorMapInput` via:
//
//	MonitorMap{ "key": MonitorArgs{...} }
type MonitorMapInput interface {
	pulumi.Input

	ToMonitorMapOutput() MonitorMapOutput
	ToMonitorMapOutputWithContext(context.Context) MonitorMapOutput
}

type MonitorMap map[string]MonitorInput

func (MonitorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Monitor)(nil)).Elem()
}

func (i MonitorMap) ToMonitorMapOutput() MonitorMapOutput {
	return i.ToMonitorMapOutputWithContext(context.Background())
}

func (i MonitorMap) ToMonitorMapOutputWithContext(ctx context.Context) MonitorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MonitorMapOutput)
}

type MonitorOutput struct{ *pulumi.OutputState }

func (MonitorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Monitor)(nil)).Elem()
}

func (o MonitorOutput) ToMonitorOutput() MonitorOutput {
	return o
}

func (o MonitorOutput) ToMonitorOutputWithContext(ctx context.Context) MonitorOutput {
	return o
}

// : Indicates whether the monitor is enabled.
func (o MonitorOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v *Monitor) pulumi.BoolOutput { return v.Active }).(pulumi.BoolOutput)
}

// : Default is `false`. Indicates whether the monitor has been marked for deletion.
func (o MonitorOutput) IsDeleted() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Monitor) pulumi.BoolPtrOutput { return v.IsDeleted }).(pulumi.BoolPtrOutput)
}

// : The name of the monitor. Defaults to an empty string if not provided.
func (o MonitorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
func (o MonitorOutput) Sensors() pulumi.StringOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringOutput { return v.Sensors }).(pulumi.StringOutput)
}

// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
func (o MonitorOutput) Sinks() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringPtrOutput { return v.Sinks }).(pulumi.StringPtrOutput)
}

// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
func (o MonitorOutput) SinksOptions() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringPtrOutput { return v.SinksOptions }).(pulumi.StringPtrOutput)
}

// : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
func (o MonitorOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// : Additional settings required for specific monitor types.
func (o MonitorOutput) Variables() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Monitor) pulumi.StringPtrOutput { return v.Variables }).(pulumi.StringPtrOutput)
}

type MonitorArrayOutput struct{ *pulumi.OutputState }

func (MonitorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Monitor)(nil)).Elem()
}

func (o MonitorArrayOutput) ToMonitorArrayOutput() MonitorArrayOutput {
	return o
}

func (o MonitorArrayOutput) ToMonitorArrayOutputWithContext(ctx context.Context) MonitorArrayOutput {
	return o
}

func (o MonitorArrayOutput) Index(i pulumi.IntInput) MonitorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Monitor {
		return vs[0].([]*Monitor)[vs[1].(int)]
	}).(MonitorOutput)
}

type MonitorMapOutput struct{ *pulumi.OutputState }

func (MonitorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Monitor)(nil)).Elem()
}

func (o MonitorMapOutput) ToMonitorMapOutput() MonitorMapOutput {
	return o
}

func (o MonitorMapOutput) ToMonitorMapOutputWithContext(ctx context.Context) MonitorMapOutput {
	return o
}

func (o MonitorMapOutput) MapIndex(k pulumi.StringInput) MonitorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Monitor {
		return vs[0].(map[string]*Monitor)[vs[1].(string)]
	}).(MonitorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MonitorInput)(nil)).Elem(), &Monitor{})
	pulumi.RegisterInputType(reflect.TypeOf((*MonitorArrayInput)(nil)).Elem(), MonitorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MonitorMapInput)(nil)).Elem(), MonitorMap{})
	pulumi.RegisterOutputType(MonitorOutput{})
	pulumi.RegisterOutputType(MonitorArrayOutput{})
	pulumi.RegisterOutputType(MonitorMapOutput{})
}
