// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package komodor

import (
	"context"
	"reflect"

	"errors"
	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a logical binding between a Komodor Role and a Komodor Policy
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/phillipedwards/pulumi-komodor/sdk/go/komodor"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			my_policy, err := komodor.NewPolicy(ctx, "my-policy", &komodor.PolicyArgs{
//				Statements: pulumi.String(`[{
//	  "actions": [
//	    "get:daemonset",
//	    "edit:cronjob",
//	    "delete:service",
//	    "edit:job"
//	  ],
//	  "resources": [{
//	    "cluster": "kind-kind",
//	    "namespaces": [
//	      "default",
//	      "komodor"
//	    ]
//	  }]
//	}]
//
// `),
//
//			})
//			if err != nil {
//				return err
//			}
//			my_role, err := komodor.NewRole(ctx, "my-role", nil)
//			if err != nil {
//				return err
//			}
//			_, err = komodor.NewPolicyRoleAttachment(ctx, "my-attachement", &komodor.PolicyRoleAttachmentArgs{
//				Policies: pulumi.StringArray{
//					my_policy.ID(),
//				},
//				Role: my_role.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type PolicyRoleAttachment struct {
	pulumi.CustomResourceState

	Name     pulumi.StringOutput      `pulumi:"name"`
	Policies pulumi.StringArrayOutput `pulumi:"policies"`
	Role     pulumi.StringOutput      `pulumi:"role"`
}

// NewPolicyRoleAttachment registers a new resource with the given unique name, arguments, and options.
func NewPolicyRoleAttachment(ctx *pulumi.Context,
	name string, args *PolicyRoleAttachmentArgs, opts ...pulumi.ResourceOption) (*PolicyRoleAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Policies == nil {
		return nil, errors.New("invalid value for required argument 'Policies'")
	}
	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PolicyRoleAttachment
	err := ctx.RegisterResource("komodor:index/policyRoleAttachment:PolicyRoleAttachment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPolicyRoleAttachment gets an existing PolicyRoleAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPolicyRoleAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PolicyRoleAttachmentState, opts ...pulumi.ResourceOption) (*PolicyRoleAttachment, error) {
	var resource PolicyRoleAttachment
	err := ctx.ReadResource("komodor:index/policyRoleAttachment:PolicyRoleAttachment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PolicyRoleAttachment resources.
type policyRoleAttachmentState struct {
	Name     *string  `pulumi:"name"`
	Policies []string `pulumi:"policies"`
	Role     *string  `pulumi:"role"`
}

type PolicyRoleAttachmentState struct {
	Name     pulumi.StringPtrInput
	Policies pulumi.StringArrayInput
	Role     pulumi.StringPtrInput
}

func (PolicyRoleAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*policyRoleAttachmentState)(nil)).Elem()
}

type policyRoleAttachmentArgs struct {
	Name     *string  `pulumi:"name"`
	Policies []string `pulumi:"policies"`
	Role     string   `pulumi:"role"`
}

// The set of arguments for constructing a PolicyRoleAttachment resource.
type PolicyRoleAttachmentArgs struct {
	Name     pulumi.StringPtrInput
	Policies pulumi.StringArrayInput
	Role     pulumi.StringInput
}

func (PolicyRoleAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*policyRoleAttachmentArgs)(nil)).Elem()
}

type PolicyRoleAttachmentInput interface {
	pulumi.Input

	ToPolicyRoleAttachmentOutput() PolicyRoleAttachmentOutput
	ToPolicyRoleAttachmentOutputWithContext(ctx context.Context) PolicyRoleAttachmentOutput
}

func (*PolicyRoleAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**PolicyRoleAttachment)(nil)).Elem()
}

func (i *PolicyRoleAttachment) ToPolicyRoleAttachmentOutput() PolicyRoleAttachmentOutput {
	return i.ToPolicyRoleAttachmentOutputWithContext(context.Background())
}

func (i *PolicyRoleAttachment) ToPolicyRoleAttachmentOutputWithContext(ctx context.Context) PolicyRoleAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRoleAttachmentOutput)
}

// PolicyRoleAttachmentArrayInput is an input type that accepts PolicyRoleAttachmentArray and PolicyRoleAttachmentArrayOutput values.
// You can construct a concrete instance of `PolicyRoleAttachmentArrayInput` via:
//
//	PolicyRoleAttachmentArray{ PolicyRoleAttachmentArgs{...} }
type PolicyRoleAttachmentArrayInput interface {
	pulumi.Input

	ToPolicyRoleAttachmentArrayOutput() PolicyRoleAttachmentArrayOutput
	ToPolicyRoleAttachmentArrayOutputWithContext(context.Context) PolicyRoleAttachmentArrayOutput
}

type PolicyRoleAttachmentArray []PolicyRoleAttachmentInput

func (PolicyRoleAttachmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PolicyRoleAttachment)(nil)).Elem()
}

func (i PolicyRoleAttachmentArray) ToPolicyRoleAttachmentArrayOutput() PolicyRoleAttachmentArrayOutput {
	return i.ToPolicyRoleAttachmentArrayOutputWithContext(context.Background())
}

func (i PolicyRoleAttachmentArray) ToPolicyRoleAttachmentArrayOutputWithContext(ctx context.Context) PolicyRoleAttachmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRoleAttachmentArrayOutput)
}

// PolicyRoleAttachmentMapInput is an input type that accepts PolicyRoleAttachmentMap and PolicyRoleAttachmentMapOutput values.
// You can construct a concrete instance of `PolicyRoleAttachmentMapInput` via:
//
//	PolicyRoleAttachmentMap{ "key": PolicyRoleAttachmentArgs{...} }
type PolicyRoleAttachmentMapInput interface {
	pulumi.Input

	ToPolicyRoleAttachmentMapOutput() PolicyRoleAttachmentMapOutput
	ToPolicyRoleAttachmentMapOutputWithContext(context.Context) PolicyRoleAttachmentMapOutput
}

type PolicyRoleAttachmentMap map[string]PolicyRoleAttachmentInput

func (PolicyRoleAttachmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PolicyRoleAttachment)(nil)).Elem()
}

func (i PolicyRoleAttachmentMap) ToPolicyRoleAttachmentMapOutput() PolicyRoleAttachmentMapOutput {
	return i.ToPolicyRoleAttachmentMapOutputWithContext(context.Background())
}

func (i PolicyRoleAttachmentMap) ToPolicyRoleAttachmentMapOutputWithContext(ctx context.Context) PolicyRoleAttachmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyRoleAttachmentMapOutput)
}

type PolicyRoleAttachmentOutput struct{ *pulumi.OutputState }

func (PolicyRoleAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PolicyRoleAttachment)(nil)).Elem()
}

func (o PolicyRoleAttachmentOutput) ToPolicyRoleAttachmentOutput() PolicyRoleAttachmentOutput {
	return o
}

func (o PolicyRoleAttachmentOutput) ToPolicyRoleAttachmentOutputWithContext(ctx context.Context) PolicyRoleAttachmentOutput {
	return o
}

func (o PolicyRoleAttachmentOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyRoleAttachment) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PolicyRoleAttachmentOutput) Policies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PolicyRoleAttachment) pulumi.StringArrayOutput { return v.Policies }).(pulumi.StringArrayOutput)
}

func (o PolicyRoleAttachmentOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyRoleAttachment) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

type PolicyRoleAttachmentArrayOutput struct{ *pulumi.OutputState }

func (PolicyRoleAttachmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PolicyRoleAttachment)(nil)).Elem()
}

func (o PolicyRoleAttachmentArrayOutput) ToPolicyRoleAttachmentArrayOutput() PolicyRoleAttachmentArrayOutput {
	return o
}

func (o PolicyRoleAttachmentArrayOutput) ToPolicyRoleAttachmentArrayOutputWithContext(ctx context.Context) PolicyRoleAttachmentArrayOutput {
	return o
}

func (o PolicyRoleAttachmentArrayOutput) Index(i pulumi.IntInput) PolicyRoleAttachmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PolicyRoleAttachment {
		return vs[0].([]*PolicyRoleAttachment)[vs[1].(int)]
	}).(PolicyRoleAttachmentOutput)
}

type PolicyRoleAttachmentMapOutput struct{ *pulumi.OutputState }

func (PolicyRoleAttachmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PolicyRoleAttachment)(nil)).Elem()
}

func (o PolicyRoleAttachmentMapOutput) ToPolicyRoleAttachmentMapOutput() PolicyRoleAttachmentMapOutput {
	return o
}

func (o PolicyRoleAttachmentMapOutput) ToPolicyRoleAttachmentMapOutputWithContext(ctx context.Context) PolicyRoleAttachmentMapOutput {
	return o
}

func (o PolicyRoleAttachmentMapOutput) MapIndex(k pulumi.StringInput) PolicyRoleAttachmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PolicyRoleAttachment {
		return vs[0].(map[string]*PolicyRoleAttachment)[vs[1].(string)]
	}).(PolicyRoleAttachmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRoleAttachmentInput)(nil)).Elem(), &PolicyRoleAttachment{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRoleAttachmentArrayInput)(nil)).Elem(), PolicyRoleAttachmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyRoleAttachmentMapInput)(nil)).Elem(), PolicyRoleAttachmentMap{})
	pulumi.RegisterOutputType(PolicyRoleAttachmentOutput{})
	pulumi.RegisterOutputType(PolicyRoleAttachmentArrayOutput{})
	pulumi.RegisterOutputType(PolicyRoleAttachmentMapOutput{})
}
