// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    /// <summary>
    /// Creates a new Komodor RBAC action
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var komo_example_pod_viewer = new Komodor.Action("komo-example-pod-viewer", new()
    ///     {
    ///         ActionName = "pod-viewer",
    ///         Description = "View pods",
    ///         Ruleset = @"[
    ///   {
    ///     \""apiGroups\"": [
    ///       \""apps\""
    ///     ],
    ///     \""resources\"": [
    ///       \""pods\""
    ///     ],
    ///     \""verbs\"": [
    ///       \""get\"",
    ///       \""list\""
    ///     ]
    ///   }
    /// ]
    /// ",
    ///     });
    /// 
    ///     var komo_example_policy = new Komodor.Policy("komo-example-policy", new()
    ///     {
    ///         Name = "komo-example-policy",
    ///         Statements = komo_example_pod_viewer.ActionName.Apply(action =&gt; @$"[{{
    ///   \""actions\"": [
    ///     \""{action}\""
    ///   ],
    ///   \""resources\"": [{{
    ///     \""cluster\"": \""komo-example-cluster\"",
    ///     \""namespaces\"": [
    ///       \""default\"",
    ///       \""kube-system\""
    ///     ]
    ///   }}]
    /// }}]
    /// "),
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [KomodorResourceType("komodor:index/action:Action")]
    public partial class Action : global::Pulumi.CustomResource
    {
        [Output("action")]
        public Output<string> ActionName { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("ruleset")]
        public Output<string> Ruleset { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Action resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Action(string name, ActionArgs args, CustomResourceOptions? options = null)
            : base("komodor:index/action:Action", name, args ?? new ActionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Action(string name, Input<string> id, ActionState? state = null, CustomResourceOptions? options = null)
            : base("komodor:index/action:Action", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/phillipedwards/pulumi-komodor/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Action resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Action Get(string name, Input<string> id, ActionState? state = null, CustomResourceOptions? options = null)
        {
            return new Action(name, id, state, options);
        }
    }

    public sealed class ActionArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<string> ActionName { get; set; } = null!;

        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        [Input("ruleset", required: true)]
        public Input<string> Ruleset { get; set; } = null!;

        public ActionArgs()
        {
        }
        public static new ActionArgs Empty => new ActionArgs();
    }

    public sealed class ActionState : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? ActionName { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("ruleset")]
        public Input<string>? Ruleset { get; set; }

        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public ActionState()
        {
        }
        public static new ActionState Empty => new ActionState();
    }
}
