// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    public static class GetKubernetes
    {
        /// <summary>
        /// Retrieves an existing Komodor Kubernetes cluster integration by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetKubernetes.Invoke(new()
        ///     {
        ///         ClusterName = "my-cluster",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetKubernetesResult> InvokeAsync(GetKubernetesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetKubernetesResult>("komodor:index/getKubernetes:getKubernetes", args ?? new GetKubernetesArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Kubernetes cluster integration by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetKubernetes.Invoke(new()
        ///     {
        ///         ClusterName = "my-cluster",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetKubernetesResult> Invoke(GetKubernetesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetKubernetesResult>("komodor:index/getKubernetes:getKubernetes", args ?? new GetKubernetesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Kubernetes cluster integration by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetKubernetes.Invoke(new()
        ///     {
        ///         ClusterName = "my-cluster",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetKubernetesResult> Invoke(GetKubernetesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetKubernetesResult>("komodor:index/getKubernetes:getKubernetes", args ?? new GetKubernetesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKubernetesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the cluster; must be unique to a Komodor account
        /// </summary>
        [Input("clusterName", required: true)]
        public string ClusterName { get; set; } = null!;

        public GetKubernetesArgs()
        {
        }
        public static new GetKubernetesArgs Empty => new GetKubernetesArgs();
    }

    public sealed class GetKubernetesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the cluster; must be unique to a Komodor account
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        public GetKubernetesInvokeArgs()
        {
        }
        public static new GetKubernetesInvokeArgs Empty => new GetKubernetesInvokeArgs();
    }


    [OutputType]
    public sealed class GetKubernetesResult
    {
        /// <summary>
        /// The name of the cluster; must be unique to a Komodor account
        /// </summary>
        public readonly string ClusterName;
        /// <summary>
        /// The id and api key of the cluster integration
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetKubernetesResult(
            string clusterName,

            string id)
        {
            ClusterName = clusterName;
            Id = id;
        }
    }
}
