// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    public static class GetPolicy
    {
        /// <summary>
        /// Retrieves an existing Komodor Policy by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetPolicy.Invoke(new()
        ///     {
        ///         Name = "my-policy",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetPolicyResult> InvokeAsync(GetPolicyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPolicyResult>("komodor:index/getPolicy:getPolicy", args ?? new GetPolicyArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Policy by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetPolicy.Invoke(new()
        ///     {
        ///         Name = "my-policy",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPolicyResult> Invoke(GetPolicyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPolicyResult>("komodor:index/getPolicy:getPolicy", args ?? new GetPolicyInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Policy by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dataK8sCluster = Komodor.GetPolicy.Invoke(new()
        ///     {
        ///         Name = "my-policy",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPolicyResult> Invoke(GetPolicyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPolicyResult>("komodor:index/getPolicy:getPolicy", args ?? new GetPolicyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPolicyArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetPolicyArgs()
        {
        }
        public static new GetPolicyArgs Empty => new GetPolicyArgs();
    }

    public sealed class GetPolicyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetPolicyInvokeArgs()
        {
        }
        public static new GetPolicyInvokeArgs Empty => new GetPolicyInvokeArgs();
    }


    [OutputType]
    public sealed class GetPolicyResult
    {
        /// <summary>
        /// The date and time of when the Policy was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The id of the policy
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        /// <summary>
        /// The policy's statements
        /// </summary>
        public readonly string Statements;
        /// <summary>
        /// The date and time of when the Policy was last updated
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetPolicyResult(
            string createdAt,

            string id,

            string name,

            string statements,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Id = id;
            Name = name;
            Statements = statements;
            UpdatedAt = updatedAt;
        }
    }
}
