// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    public static class GetRole
    {
        /// <summary>
        /// Retrieves an existing Komodor Role by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var role = Komodor.GetRole.Invoke(new()
        ///     {
        ///         Name = "my-role",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetRoleResult> InvokeAsync(GetRoleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRoleResult>("komodor:index/getRole:getRole", args ?? new GetRoleArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Role by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var role = Komodor.GetRole.Invoke(new()
        ///     {
        ///         Name = "my-role",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRoleResult> Invoke(GetRoleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleResult>("komodor:index/getRole:getRole", args ?? new GetRoleInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves an existing Komodor Role by name
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Komodor = Pulumi.Komodor;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var role = Komodor.GetRole.Invoke(new()
        ///     {
        ///         Name = "my-role",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRoleResult> Invoke(GetRoleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleResult>("komodor:index/getRole:getRole", args ?? new GetRoleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRoleArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetRoleArgs()
        {
        }
        public static new GetRoleArgs Empty => new GetRoleArgs();
    }

    public sealed class GetRoleInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetRoleInvokeArgs()
        {
        }
        public static new GetRoleInvokeArgs Empty => new GetRoleInvokeArgs();
    }


    [OutputType]
    public sealed class GetRoleResult
    {
        /// <summary>
        /// The date and time of when the Role was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The id of the role
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Is default role
        /// </summary>
        public readonly bool IsDefault;
        public readonly string Name;
        /// <summary>
        /// The date and time of when the Role was last updated
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetRoleResult(
            string createdAt,

            string id,

            bool isDefault,

            string name,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Id = id;
            IsDefault = isDefault;
            Name = name;
            UpdatedAt = updatedAt;
        }
    }
}
