// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    /// <summary>
    /// Creates a new Komodor integration with a Kubernetes cluster.
    /// 
    /// This integration allows Komodor to monitor and analyze the cluster's activity.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var k8sCluster = new Komodor.Kubernetes("k8sCluster", new()
    ///     {
    ///         ClusterName = "my-cluster",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [KomodorResourceType("komodor:index/kubernetes:Kubernetes")]
    public partial class Kubernetes : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the Kubernetes cluster
        /// </summary>
        [Output("clusterName")]
        public Output<string> ClusterName { get; private set; } = null!;


        /// <summary>
        /// Create a Kubernetes resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Kubernetes(string name, KubernetesArgs args, CustomResourceOptions? options = null)
            : base("komodor:index/kubernetes:Kubernetes", name, args ?? new KubernetesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Kubernetes(string name, Input<string> id, KubernetesState? state = null, CustomResourceOptions? options = null)
            : base("komodor:index/kubernetes:Kubernetes", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Kubernetes resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Kubernetes Get(string name, Input<string> id, KubernetesState? state = null, CustomResourceOptions? options = null)
        {
            return new Kubernetes(name, id, state, options);
        }
    }

    public sealed class KubernetesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Kubernetes cluster
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        public KubernetesArgs()
        {
        }
        public static new KubernetesArgs Empty => new KubernetesArgs();
    }

    public sealed class KubernetesState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Kubernetes cluster
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        public KubernetesState()
        {
        }
        public static new KubernetesState Empty => new KubernetesState();
    }
}
