// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    /// <summary>
    /// Creates a new **Komodor monitor** to observe, detect, and analyze failures across your infrastructure. This resource allows you to define the parameters for monitoring specific components in your Kubernetes clusters and other infrastructure.
    /// 
    /// ***
    /// 
    /// ## Example Usage
    /// 
    /// ### Deployment Monitor
    /// 
    /// ### Valid Configurations:
    /// - **Valid Sinks**: `Slack`, `Teams`, `Webhook`
    /// - **Valid notifyOn Options**:
    ///   - `"Failure"`
    ///   - `"Successful"`
    ///   - `"All"`
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example_deploy_monitor = new Komodor.Monitor("example-deploy-monitor", new()
    ///     {
    ///         Active = true,
    ///         Sensors = @"[{
    ///   ""cluster"": ""kind-kind"",
    ///   ""exclude"": {
    ///     ""namespaces"": [""komodor""]
    ///   },
    ///   ""namespaces"": [""default""]
    /// }]
    /// 
    /// ",
    ///         Sinks = @"{
    ///   ""slack"": [""deployment-alerts""],
    ///   ""teams"": [""Platform-Team""]
    /// }
    /// 
    /// ",
    ///         SinksOptions = @"{
    ///   ""notifyOn"": [""Failure"", ""Successful""]
    /// }
    /// 
    /// ",
    ///         Type = "deploy",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// ### Availability Monitor
    /// 
    /// ### Valid Configurations:
    /// - **Valid Sinks**: `Slack`, `Teams`, `Opsgenie`, `Pagerduty`, `Webhook`
    /// - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
    /// - **Valid Categories for variables.categories**:
    ///   - `"Creating/Initializing"`
    ///   - `"Scheduling"`
    ///   - `"Container Creation"`
    ///   - `"NonZeroExitCode"`
    ///   - `"Unhealthy - failed probes"`
    ///   - `"OOMKilled"`
    ///   - `"BackOff"`
    ///   - `"Infrastructure"`
    ///   - `"Image"`
    ///   - `"Volume/Secret/ConfigMap"`
    ///   - `"Pod Termination"`
    ///   - `"Completed"`
    ///   - `"Other"`
    /// - **Valid notifyOn Options**: `["*"]`
    ///   - `["*"]` (all categories)
    ///   - Or any one of the following:
    ///     - `"Creating/Initializing"`
    ///     - `"Scheduling"`
    ///     - `"Container Creation"`
    ///     - `"NonZeroExitCode"`
    ///     - `"Unhealthy - failed probes"`
    ///     - `"OOMKilled"`
    ///     - `"BackOff"`
    ///     - `"Infrastructure"`
    ///     - `"Image"`
    ///     - `"Volume/Secret/ConfigMap"`
    ///     - `"Pod Termination"`
    ///     - `"Completed"`
    ///     - `"Other"`
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example_availability_monitor = new Komodor.Monitor("example-availability-monitor", new()
    ///     {
    ///         Active = true,
    ///         Sensors = @"[{
    ///   ""cluster"": ""kind-kind"",
    ///   ""exclude"": {
    ///     ""services"": [""default/excluded-service""]
    ///   },
    ///   ""services"": [""default/important-service""],
    ///   ""condition"": ""and"",
    ///   ""namespaces"": [""default""]
    /// }]
    /// 
    /// ",
    ///         Sinks = @"{
    ///   ""slack"": [""availability-alerts""],
    ///   ""teams"": [""SRE-Team""]
    /// }
    /// 
    /// ",
    ///         SinksOptions = @"{
    ///   ""notifyOn"": [""*""]
    /// }
    /// 
    /// ",
    ///         Type = "availability",
    ///         Variables = @"{
    ///   ""categories"": [""Creating/Initializing"", ""Unhealthy - failed probes""],
    ///   ""duration"": 30,
    ///   ""minAvailable"": ""100%""
    /// }
    /// 
    /// ",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// ### Node Monitor
    /// 
    /// ### Valid Configurations:
    /// - **Valid Sinks**: `Slack`, `Teams`, `Opsgenie`, `Pagerduty`, `Webhook`
    /// - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
    /// - **Valid NodeCreationThreshold: Should be in the format of `"3m"` (3 minutes) or `"5s"` (5 seconds).
    /// - **Valid Variables**:
    ///   - `Duration`: Required
    ///   - `nodeCreationThreshold`: Required
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example_node_monitor = new Komodor.Monitor("example-node-monitor", new()
    ///     {
    ///         Active = true,
    ///         Sensors = @"[{
    ///   ""cluster"": ""kind-kind""
    /// }]
    /// 
    /// ",
    ///         Sinks = @"{
    ///   ""slack"": [""node-alerts""]
    /// }
    /// 
    /// ",
    ///         Type = "node",
    ///         Variables = @"{
    ///   ""duration"": 60,
    ///   ""nodeCreationThreshold"": ""10m""
    /// }
    /// 
    /// ",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// ### Workflow Monitor
    /// 
    /// ### Valid Configurations:
    /// - **Valid Sinks**: `Slack`, `Teams`, `Opsgenie`, `Pagerduty`, `Webhook`
    /// - **Valid notifyOn Options**: None (not applicable for workflows)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example_workflow_monitor = new Komodor.Monitor("example-workflow-monitor", new()
    ///     {
    ///         Active = true,
    ///         Sensors = @"[{
    ///   ""cluster"": ""kind-kind"",
    ///   ""namespaces"": [""workflow-namespace""]
    /// }]
    /// 
    /// ",
    ///         Sinks = @"{
    ///   ""slack"": [""workflow-alerts""],
    ///   ""webhook"": [""webhook-url""]
    /// }
    /// 
    /// ",
    ///         Type = "workflow",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// </summary>
    [KomodorResourceType("komodor:index/monitor:Monitor")]
    public partial class Monitor : global::Pulumi.CustomResource
    {
        /// <summary>
        /// : Indicates whether the monitor is enabled.
        /// </summary>
        [Output("active")]
        public Output<bool> Active { get; private set; } = null!;

        /// <summary>
        /// : Default is `False`. Indicates whether the monitor has been marked for deletion.
        /// </summary>
        [Output("isDeleted")]
        public Output<bool?> IsDeleted { get; private set; } = null!;

        /// <summary>
        /// : The name of the monitor. Defaults to an empty string if not provided.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        /// </summary>
        [Output("sensors")]
        public Output<string> Sensors { get; private set; } = null!;

        /// <summary>
        /// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        /// </summary>
        [Output("sinks")]
        public Output<string?> Sinks { get; private set; } = null!;

        /// <summary>
        /// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        /// </summary>
        [Output("sinksOptions")]
        public Output<string?> SinksOptions { get; private set; } = null!;

        /// <summary>
        /// : The monitor type. Must be one of: `Availability`, `Node`, `PVC`, `Job`, `cronJob`, `Deploy`, or `Workflow`.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// : Additional settings required for specific monitor types.
        /// </summary>
        [Output("variables")]
        public Output<string?> Variables { get; private set; } = null!;


        /// <summary>
        /// Create a Monitor resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Monitor(string name, MonitorArgs args, CustomResourceOptions? options = null)
            : base("komodor:index/monitor:Monitor", name, args ?? new MonitorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Monitor(string name, Input<string> id, MonitorState? state = null, CustomResourceOptions? options = null)
            : base("komodor:index/monitor:Monitor", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Monitor resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Monitor Get(string name, Input<string> id, MonitorState? state = null, CustomResourceOptions? options = null)
        {
            return new Monitor(name, id, state, options);
        }
    }

    public sealed class MonitorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// : Indicates whether the monitor is enabled.
        /// </summary>
        [Input("active", required: true)]
        public Input<bool> Active { get; set; } = null!;

        /// <summary>
        /// : Default is `False`. Indicates whether the monitor has been marked for deletion.
        /// </summary>
        [Input("isDeleted")]
        public Input<bool>? IsDeleted { get; set; }

        /// <summary>
        /// : The name of the monitor. Defaults to an empty string if not provided.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        /// </summary>
        [Input("sensors", required: true)]
        public Input<string> Sensors { get; set; } = null!;

        /// <summary>
        /// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        /// </summary>
        [Input("sinks")]
        public Input<string>? Sinks { get; set; }

        /// <summary>
        /// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        /// </summary>
        [Input("sinksOptions")]
        public Input<string>? SinksOptions { get; set; }

        /// <summary>
        /// : The monitor type. Must be one of: `Availability`, `Node`, `PVC`, `Job`, `cronJob`, `Deploy`, or `Workflow`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// : Additional settings required for specific monitor types.
        /// </summary>
        [Input("variables")]
        public Input<string>? Variables { get; set; }

        public MonitorArgs()
        {
        }
        public static new MonitorArgs Empty => new MonitorArgs();
    }

    public sealed class MonitorState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// : Indicates whether the monitor is enabled.
        /// </summary>
        [Input("active")]
        public Input<bool>? Active { get; set; }

        /// <summary>
        /// : Default is `False`. Indicates whether the monitor has been marked for deletion.
        /// </summary>
        [Input("isDeleted")]
        public Input<bool>? IsDeleted { get; set; }

        /// <summary>
        /// : The name of the monitor. Defaults to an empty string if not provided.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        /// </summary>
        [Input("sensors")]
        public Input<string>? Sensors { get; set; }

        /// <summary>
        /// : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        /// </summary>
        [Input("sinks")]
        public Input<string>? Sinks { get; set; }

        /// <summary>
        /// : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        /// </summary>
        [Input("sinksOptions")]
        public Input<string>? SinksOptions { get; set; }

        /// <summary>
        /// : The monitor type. Must be one of: `Availability`, `Node`, `PVC`, `Job`, `cronJob`, `Deploy`, or `Workflow`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// : Additional settings required for specific monitor types.
        /// </summary>
        [Input("variables")]
        public Input<string>? Variables { get; set; }

        public MonitorState()
        {
        }
        public static new MonitorState Empty => new MonitorState();
    }
}
