// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    /// <summary>
    /// Creates a Komodor RBAC Policy
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var my_policy = new Komodor.Policy("my-policy", new()
    ///     {
    ///         Name = "my-policy",
    ///         Statements = @"[{
    ///   \""actions\"": [
    ///     \""get:daemonset\"",
    ///     \""edit:cronjob\"",
    ///     \""delete:service\"",
    ///     \""edit:job\""
    ///   ],
    ///   \""resources\"": [{
    ///     \""cluster\"": \""kind-kind\"",
    ///     \""namespaces\"": [
    ///       \""default\"",
    ///       \""komodor\""
    ///     ]
    ///   }]
    /// }]
    /// ",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Dyanmic Tags
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // This example shows how to create a policy with dynamic tags.
    ///     // Dynamic tags feature is not available by default.
    ///     // When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
    ///     var komo_example_dynamic_tags_policy = new Komodor.Policy("komo-example-dynamic-tags-policy", new()
    ///     {
    ///         Name = "komo-example-dynamic-tags-policy",
    ///         Type = "dynamic_tag",
    ///         Tags = 
    ///         {
    ///             { "team", "super-heroes" },
    ///         },
    ///         Statements = @"[{
    ///   \""actions\"": [
    ///     \""view:all\""
    ///   ],
    ///   \""resources\"": []
    /// }]
    /// ",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Wildcard Namespace
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // This example shows how to create a policy with a wildcard namespace pattern.
    ///     // wildcard policy type is not available by default.
    ///     // When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
    ///     var komo_example_wildcard_policy = new Komodor.Policy("komo-example-wildcard-policy", new()
    ///     {
    ///         Name = "komo-example-wildcard-policy",
    ///         Type = "wildcard",
    ///         Statements = @"[{
    ///   \""actions\"": [
    ///     \""view:all\""
    ///   ],
    ///   \""resources\"": [{
    ///     \""cluster\"": \""komo-example-cluster\"",
    ///     \""namespacePattern\"": \""prod-*\""
    ///   }]
    /// }]
    /// ",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### With komodor.Action
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var komo_example_pod_viewer = new Komodor.Action("komo-example-pod-viewer", new()
    ///     {
    ///         ActionName = "pod-viewer",
    ///         Description = "View pods",
    ///         Ruleset = @"[
    ///   {
    ///     \""apiGroups\"": [
    ///       \""apps\""
    ///     ],
    ///     \""resources\"": [
    ///       \""pods\""
    ///     ],
    ///     \""verbs\"": [
    ///       \""get\"",
    ///       \""list\""
    ///     ]
    ///   }
    /// ]
    /// ",
    ///     });
    /// 
    ///     var komo_example_policy = new Komodor.Policy("komo-example-policy", new()
    ///     {
    ///         Name = "komo-example-policy",
    ///         Statements = komo_example_pod_viewer.ActionName.Apply(action =&gt; @$"[{{
    ///   \""actions\"": [
    ///     \""{action}\""
    ///   ],
    ///   \""resources\"": [{{
    ///     \""cluster\"": \""komo-example-cluster\"",
    ///     \""namespaces\"": [
    ///       \""default\"",
    ///       \""kube-system\""
    ///     ]
    ///   }}]
    /// }}]
    /// "),
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [KomodorResourceType("komodor:index/policy:Policy")]
    public partial class Policy : global::Pulumi.CustomResource
    {
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("statements")]
        public Output<string> Statements { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Policy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Policy(string name, PolicyArgs args, CustomResourceOptions? options = null)
            : base("komodor:index/policy:Policy", name, args ?? new PolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Policy(string name, Input<string> id, PolicyState? state = null, CustomResourceOptions? options = null)
            : base("komodor:index/policy:Policy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/phillipedwards/pulumi-komodor/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Policy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Policy Get(string name, Input<string> id, PolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new Policy(name, id, state, options);
        }
    }

    public sealed class PolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("statements", required: true)]
        public Input<string> Statements { get; set; } = null!;

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public PolicyArgs()
        {
        }
        public static new PolicyArgs Empty => new PolicyArgs();
    }

    public sealed class PolicyState : global::Pulumi.ResourceArgs
    {
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("statements")]
        public Input<string>? Statements { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public PolicyState()
        {
        }
        public static new PolicyState Empty => new PolicyState();
    }
}
