// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Komodor
{
    /// <summary>
    /// Creates a logical binding between a Komodor Role and a Komodor Policy
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Komodor = Pulumi.Komodor;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var my_policy = new Komodor.Policy("my-policy", new()
    ///     {
    ///         Statements = @"[{
    ///   ""actions"": [
    ///     ""get:daemonset"",
    ///     ""edit:cronjob"",
    ///     ""delete:service"",
    ///     ""edit:job""
    ///   ],
    ///   ""resources"": [{
    ///     ""cluster"": ""kind-kind"",
    ///     ""namespaces"": [
    ///       ""default"",
    ///       ""komodor""
    ///     ]
    ///   }]
    /// }]
    /// ",
    ///     });
    /// 
    ///     var my_role = new Komodor.Role("my-role");
    /// 
    ///     var my_attachement = new Komodor.PolicyRoleAttachment("my-attachement", new()
    ///     {
    ///         Policies = new[]
    ///         {
    ///             my_policy.Id,
    ///         },
    ///         Role = my_role.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [KomodorResourceType("komodor:index/policyRoleAttachment:PolicyRoleAttachment")]
    public partial class PolicyRoleAttachment : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("policies")]
        public Output<ImmutableArray<string>> Policies { get; private set; } = null!;

        [Output("role")]
        public Output<string> Role { get; private set; } = null!;


        /// <summary>
        /// Create a PolicyRoleAttachment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyRoleAttachment(string name, PolicyRoleAttachmentArgs args, CustomResourceOptions? options = null)
            : base("komodor:index/policyRoleAttachment:PolicyRoleAttachment", name, args ?? new PolicyRoleAttachmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PolicyRoleAttachment(string name, Input<string> id, PolicyRoleAttachmentState? state = null, CustomResourceOptions? options = null)
            : base("komodor:index/policyRoleAttachment:PolicyRoleAttachment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyRoleAttachment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyRoleAttachment Get(string name, Input<string> id, PolicyRoleAttachmentState? state = null, CustomResourceOptions? options = null)
        {
            return new PolicyRoleAttachment(name, id, state, options);
        }
    }

    public sealed class PolicyRoleAttachmentArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policies", required: true)]
        private InputList<string>? _policies;
        public InputList<string> Policies
        {
            get => _policies ?? (_policies = new InputList<string>());
            set => _policies = value;
        }

        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        public PolicyRoleAttachmentArgs()
        {
        }
        public static new PolicyRoleAttachmentArgs Empty => new PolicyRoleAttachmentArgs();
    }

    public sealed class PolicyRoleAttachmentState : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policies")]
        private InputList<string>? _policies;
        public InputList<string> Policies
        {
            get => _policies ?? (_policies = new InputList<string>());
            set => _policies = value;
        }

        [Input("role")]
        public Input<string>? Role { get; set; }

        public PolicyRoleAttachmentState()
        {
        }
        public static new PolicyRoleAttachmentState Empty => new PolicyRoleAttachmentState();
    }
}
