# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .action import *
from .get_kubernetes import *
from .get_policy import *
from .get_role import *
from .kubernetes import *
from .monitor import *
from .policy import *
from .policy_role_attachment import *
from .provider import *
from .role import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_komodor.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_komodor.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "komodor",
  "mod": "index/action",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/action:Action": "Action"
  }
 },
 {
  "pkg": "komodor",
  "mod": "index/kubernetes",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/kubernetes:Kubernetes": "Kubernetes"
  }
 },
 {
  "pkg": "komodor",
  "mod": "index/monitor",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/monitor:Monitor": "Monitor"
  }
 },
 {
  "pkg": "komodor",
  "mod": "index/policy",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "komodor",
  "mod": "index/policyRoleAttachment",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/policyRoleAttachment:PolicyRoleAttachment": "PolicyRoleAttachment"
  }
 },
 {
  "pkg": "komodor",
  "mod": "index/role",
  "fqn": "pulumi_komodor",
  "classes": {
   "komodor:index/role:Role": "Role"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "komodor",
  "token": "pulumi:providers:komodor",
  "fqn": "pulumi_komodor",
  "class": "Provider"
 }
]
"""
)
