# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['KubernetesArgs', 'Kubernetes']

@pulumi.input_type
class KubernetesArgs:
    def __init__(__self__, *,
                 cluster_name: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a Kubernetes resource.

        :param pulumi.Input[_builtins.str] cluster_name: The name of the Kubernetes cluster
        """
        pulumi.set(__self__, "cluster_name", cluster_name)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the Kubernetes cluster
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_name", value)


@pulumi.input_type
class _KubernetesState:
    def __init__(__self__, *,
                 cluster_name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Kubernetes resources.

        :param pulumi.Input[_builtins.str] cluster_name: The name of the Kubernetes cluster
        """
        if cluster_name is not None:
            pulumi.set(__self__, "cluster_name", cluster_name)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the Kubernetes cluster
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cluster_name", value)


@pulumi.type_token("komodor:index/kubernetes:Kubernetes")
class Kubernetes(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Creates a new Komodor integration with a Kubernetes cluster.

        This integration allows Komodor to monitor and analyze the cluster's activity.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        k8s_cluster = komodor.Kubernetes("k8s_cluster", cluster_name="my-cluster")
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster_name: The name of the Kubernetes cluster
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: KubernetesArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates a new Komodor integration with a Kubernetes cluster.

        This integration allows Komodor to monitor and analyze the cluster's activity.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        k8s_cluster = komodor.Kubernetes("k8s_cluster", cluster_name="my-cluster")
        ```


        :param str resource_name: The name of the resource.
        :param KubernetesArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(KubernetesArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = KubernetesArgs.__new__(KubernetesArgs)

            if cluster_name is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_name'")
            __props__.__dict__["cluster_name"] = cluster_name
        super(Kubernetes, __self__).__init__(
            'komodor:index/kubernetes:Kubernetes',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            cluster_name: pulumi.Input[Optional[_builtins.str]] = None) -> 'Kubernetes':
        """
        Get an existing Kubernetes resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster_name: The name of the Kubernetes cluster
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _KubernetesState.__new__(_KubernetesState)

        __props__.__dict__["cluster_name"] = cluster_name
        return Kubernetes(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the Kubernetes cluster
        """
        return pulumi.get(self, "cluster_name")

