# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['MonitorArgs', 'Monitor']

@pulumi.input_type
class MonitorArgs:
    def __init__(__self__, *,
                 active: pulumi.Input[_builtins.bool],
                 sensors: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 is_deleted: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks_options: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Monitor resource.

        :param pulumi.Input[_builtins.bool] active: : Indicates whether the monitor is enabled.
        :param pulumi.Input[_builtins.str] sensors: : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        :param pulumi.Input[_builtins.str] type: : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        :param pulumi.Input[_builtins.bool] is_deleted: : Default is `false`. Indicates whether the monitor has been marked for deletion.
        :param pulumi.Input[_builtins.str] name: : The name of the monitor. Defaults to an empty string if not provided.
        :param pulumi.Input[_builtins.str] sinks: : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        :param pulumi.Input[_builtins.str] sinks_options: : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        :param pulumi.Input[_builtins.str] variables: : Additional settings required for specific monitor types.
        """
        pulumi.set(__self__, "active", active)
        pulumi.set(__self__, "sensors", sensors)
        pulumi.set(__self__, "type", type)
        if is_deleted is not None:
            pulumi.set(__self__, "is_deleted", is_deleted)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if sinks is not None:
            pulumi.set(__self__, "sinks", sinks)
        if sinks_options is not None:
            pulumi.set(__self__, "sinks_options", sinks_options)
        if variables is not None:
            pulumi.set(__self__, "variables", variables)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Input[_builtins.bool]:
        """
        : Indicates whether the monitor is enabled.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def sensors(self) -> pulumi.Input[_builtins.str]:
        """
        : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        """
        return pulumi.get(self, "sensors")

    @sensors.setter
    def sensors(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "sensors", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="isDeleted")
    def is_deleted(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        : Default is `false`. Indicates whether the monitor has been marked for deletion.
        """
        return pulumi.get(self, "is_deleted")

    @is_deleted.setter
    def is_deleted(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_deleted", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : The name of the monitor. Defaults to an empty string if not provided.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def sinks(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        """
        return pulumi.get(self, "sinks")

    @sinks.setter
    def sinks(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sinks", value)

    @_builtins.property
    @pulumi.getter(name="sinksOptions")
    def sinks_options(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        """
        return pulumi.get(self, "sinks_options")

    @sinks_options.setter
    def sinks_options(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sinks_options", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Additional settings required for specific monitor types.
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "variables", value)


@pulumi.input_type
class _MonitorState:
    def __init__(__self__, *,
                 active: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_deleted: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 sensors: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks_options: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Monitor resources.

        :param pulumi.Input[_builtins.bool] active: : Indicates whether the monitor is enabled.
        :param pulumi.Input[_builtins.bool] is_deleted: : Default is `false`. Indicates whether the monitor has been marked for deletion.
        :param pulumi.Input[_builtins.str] name: : The name of the monitor. Defaults to an empty string if not provided.
        :param pulumi.Input[_builtins.str] sensors: : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        :param pulumi.Input[_builtins.str] sinks: : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        :param pulumi.Input[_builtins.str] sinks_options: : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        :param pulumi.Input[_builtins.str] type: : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        :param pulumi.Input[_builtins.str] variables: : Additional settings required for specific monitor types.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if is_deleted is not None:
            pulumi.set(__self__, "is_deleted", is_deleted)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if sensors is not None:
            pulumi.set(__self__, "sensors", sensors)
        if sinks is not None:
            pulumi.set(__self__, "sinks", sinks)
        if sinks_options is not None:
            pulumi.set(__self__, "sinks_options", sinks_options)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if variables is not None:
            pulumi.set(__self__, "variables", variables)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        : Indicates whether the monitor is enabled.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter(name="isDeleted")
    def is_deleted(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        : Default is `false`. Indicates whether the monitor has been marked for deletion.
        """
        return pulumi.get(self, "is_deleted")

    @is_deleted.setter
    def is_deleted(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_deleted", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : The name of the monitor. Defaults to an empty string if not provided.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def sensors(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        """
        return pulumi.get(self, "sensors")

    @sensors.setter
    def sensors(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sensors", value)

    @_builtins.property
    @pulumi.getter
    def sinks(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        """
        return pulumi.get(self, "sinks")

    @sinks.setter
    def sinks(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sinks", value)

    @_builtins.property
    @pulumi.getter(name="sinksOptions")
    def sinks_options(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        """
        return pulumi.get(self, "sinks_options")

    @sinks_options.setter
    def sinks_options(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sinks_options", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        : Additional settings required for specific monitor types.
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "variables", value)


@pulumi.type_token("komodor:index/monitor:Monitor")
class Monitor(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_deleted: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 sensors: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks_options: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Creates a new **Komodor monitor** to observe, detect, and analyze failures across your infrastructure. This resource allows you to define the parameters for monitoring specific components in your Kubernetes clusters and other infrastructure.

        ***

        ## Example Usage

        ### Deployment Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `webhook`
        - **Valid notifyOn Options**:
          - `"Failure"`
          - `"Successful"`
          - `"All"`

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_deploy_monitor = komodor.Monitor("example-deploy-monitor",
            name="example-deploy-monitor",
            type="deploy",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"exclude\\": {
            \\"namespaces\\": [\\"komodor\\"]
          },
          \\"namespaces\\": [\\"default\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"deployment-alerts\\"],
          \\"teams\\": [\\"Platform-Team\\"]
        }
        \"\"\",
            sinks_options=\"\"\"{
          \\"notifyOn\\": [\\"Failure\\", \\"Successful\\"]
        }
        \"\"\")
        ```

        ***

        ### Availability Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
        - **Valid Categories for variables.categories**:
          - `"Creating/Initializing"`
          - `"Scheduling"`
          - `"Container Creation"`
          - `"NonZeroExitCode"`
          - `"Unhealthy - failed probes"`
          - `"OOMKilled"`
          - `"BackOff"`
          - `"Infrastructure"`
          - `"Image"`
          - `"Volume/Secret/ConfigMap"`
          - `"Pod Termination"`
          - `"Completed"`
          - `"Other"`
        - **Valid notifyOn Options**: `["*"]`
          - `["*"]` (all categories)
          - Or any one of the following:
            - `"Creating/Initializing"`
            - `"Scheduling"`
            - `"Container Creation"`
            - `"NonZeroExitCode"`
            - `"Unhealthy - failed probes"`
            - `"OOMKilled"`
            - `"BackOff"`
            - `"Infrastructure"`
            - `"Image"`
            - `"Volume/Secret/ConfigMap"`
            - `"Pod Termination"`
            - `"Completed"`
            - `"Other"`

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_availability_monitor = komodor.Monitor("example-availability-monitor",
            name="example-availability-monitor",
            type="availability",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"exclude\\": {
            \\"services\\": [\\"default/excluded-service\\"]
          },
          \\"services\\": [\\"default/important-service\\"],
          \\"condition\\": \\"and\\",
          \\"namespaces\\": [\\"default\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"availability-alerts\\"],
          \\"teams\\": [\\"SRE-Team\\"]
        }
        \"\"\",
            variables=\"\"\"{
          \\"categories\\": [\\"Creating/Initializing\\", \\"Unhealthy - failed probes\\"],
          \\"duration\\": 30,
          \\"minAvailable\\": \\"100%\\"
        }
        \"\"\",
            sinks_options=\"\"\"{
          \\"notifyOn\\": [\\"*\\"]
        }
        \"\"\")
        ```

        ***

        ### Node Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
        - **Valid NodeCreationThreshold: Should be in the format of `"3m"` (3 minutes) or `"5s"` (5 seconds).
        - **Valid Variables**:
          - `duration`: Required
          - `nodeCreationThreshold`: Required

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_node_monitor = komodor.Monitor("example-node-monitor",
            name="example-node-monitor",
            type="node",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\"
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"node-alerts\\"]
        }
        \"\"\",
            variables=\"\"\"{
          \\"duration\\": 60,
          \\"nodeCreationThreshold\\": \\"10m\\"
        }
        \"\"\")
        ```

        ***

        ### Workflow Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid notifyOn Options**: None (not applicable for workflows)

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_workflow_monitor = komodor.Monitor("example-workflow-monitor",
            name="example-workflow-monitor",
            type="workflow",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"namespaces\\": [\\"workflow-namespace\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"workflow-alerts\\"],
          \\"webhook\\": [\\"webhook-url\\"]
        }
        \"\"\")
        ```

        ***


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: : Indicates whether the monitor is enabled.
        :param pulumi.Input[_builtins.bool] is_deleted: : Default is `false`. Indicates whether the monitor has been marked for deletion.
        :param pulumi.Input[_builtins.str] name: : The name of the monitor. Defaults to an empty string if not provided.
        :param pulumi.Input[_builtins.str] sensors: : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        :param pulumi.Input[_builtins.str] sinks: : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        :param pulumi.Input[_builtins.str] sinks_options: : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        :param pulumi.Input[_builtins.str] type: : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        :param pulumi.Input[_builtins.str] variables: : Additional settings required for specific monitor types.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: MonitorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates a new **Komodor monitor** to observe, detect, and analyze failures across your infrastructure. This resource allows you to define the parameters for monitoring specific components in your Kubernetes clusters and other infrastructure.

        ***

        ## Example Usage

        ### Deployment Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `webhook`
        - **Valid notifyOn Options**:
          - `"Failure"`
          - `"Successful"`
          - `"All"`

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_deploy_monitor = komodor.Monitor("example-deploy-monitor",
            name="example-deploy-monitor",
            type="deploy",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"exclude\\": {
            \\"namespaces\\": [\\"komodor\\"]
          },
          \\"namespaces\\": [\\"default\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"deployment-alerts\\"],
          \\"teams\\": [\\"Platform-Team\\"]
        }
        \"\"\",
            sinks_options=\"\"\"{
          \\"notifyOn\\": [\\"Failure\\", \\"Successful\\"]
        }
        \"\"\")
        ```

        ***

        ### Availability Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
        - **Valid Categories for variables.categories**:
          - `"Creating/Initializing"`
          - `"Scheduling"`
          - `"Container Creation"`
          - `"NonZeroExitCode"`
          - `"Unhealthy - failed probes"`
          - `"OOMKilled"`
          - `"BackOff"`
          - `"Infrastructure"`
          - `"Image"`
          - `"Volume/Secret/ConfigMap"`
          - `"Pod Termination"`
          - `"Completed"`
          - `"Other"`
        - **Valid notifyOn Options**: `["*"]`
          - `["*"]` (all categories)
          - Or any one of the following:
            - `"Creating/Initializing"`
            - `"Scheduling"`
            - `"Container Creation"`
            - `"NonZeroExitCode"`
            - `"Unhealthy - failed probes"`
            - `"OOMKilled"`
            - `"BackOff"`
            - `"Infrastructure"`
            - `"Image"`
            - `"Volume/Secret/ConfigMap"`
            - `"Pod Termination"`
            - `"Completed"`
            - `"Other"`

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_availability_monitor = komodor.Monitor("example-availability-monitor",
            name="example-availability-monitor",
            type="availability",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"exclude\\": {
            \\"services\\": [\\"default/excluded-service\\"]
          },
          \\"services\\": [\\"default/important-service\\"],
          \\"condition\\": \\"and\\",
          \\"namespaces\\": [\\"default\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"availability-alerts\\"],
          \\"teams\\": [\\"SRE-Team\\"]
        }
        \"\"\",
            variables=\"\"\"{
          \\"categories\\": [\\"Creating/Initializing\\", \\"Unhealthy - failed probes\\"],
          \\"duration\\": 30,
          \\"minAvailable\\": \\"100%\\"
        }
        \"\"\",
            sinks_options=\"\"\"{
          \\"notifyOn\\": [\\"*\\"]
        }
        \"\"\")
        ```

        ***

        ### Node Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
        - **Valid NodeCreationThreshold: Should be in the format of `"3m"` (3 minutes) or `"5s"` (5 seconds).
        - **Valid Variables**:
          - `duration`: Required
          - `nodeCreationThreshold`: Required

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_node_monitor = komodor.Monitor("example-node-monitor",
            name="example-node-monitor",
            type="node",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\"
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"node-alerts\\"]
        }
        \"\"\",
            variables=\"\"\"{
          \\"duration\\": 60,
          \\"nodeCreationThreshold\\": \\"10m\\"
        }
        \"\"\")
        ```

        ***

        ### Workflow Monitor

        ### Valid Configurations:
        - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
        - **Valid notifyOn Options**: None (not applicable for workflows)

        ```python
        import pulumi
        import pulumi_komodor as komodor

        example_workflow_monitor = komodor.Monitor("example-workflow-monitor",
            name="example-workflow-monitor",
            type="workflow",
            active=True,
            sensors=\"\"\"[{
          \\"cluster\\": \\"kind-kind\\",
          \\"namespaces\\": [\\"workflow-namespace\\"]
        }]
        \"\"\",
            sinks=\"\"\"{
          \\"slack\\": [\\"workflow-alerts\\"],
          \\"webhook\\": [\\"webhook-url\\"]
        }
        \"\"\")
        ```

        ***


        :param str resource_name: The name of the resource.
        :param MonitorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(MonitorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_deleted: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 sensors: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks: pulumi.Input[Optional[_builtins.str]] = None,
                 sinks_options: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = MonitorArgs.__new__(MonitorArgs)

            if active is None and not opts.urn:
                raise TypeError("Missing required property 'active'")
            __props__.__dict__["active"] = active
            __props__.__dict__["is_deleted"] = is_deleted
            __props__.__dict__["name"] = name
            if sensors is None and not opts.urn:
                raise TypeError("Missing required property 'sensors'")
            __props__.__dict__["sensors"] = sensors
            __props__.__dict__["sinks"] = sinks
            __props__.__dict__["sinks_options"] = sinks_options
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["variables"] = variables
        super(Monitor, __self__).__init__(
            'komodor:index/monitor:Monitor',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            active: pulumi.Input[Optional[_builtins.bool]] = None,
            is_deleted: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            sensors: pulumi.Input[Optional[_builtins.str]] = None,
            sinks: pulumi.Input[Optional[_builtins.str]] = None,
            sinks_options: pulumi.Input[Optional[_builtins.str]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None,
            variables: pulumi.Input[Optional[_builtins.str]] = None) -> 'Monitor':
        """
        Get an existing Monitor resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: : Indicates whether the monitor is enabled.
        :param pulumi.Input[_builtins.bool] is_deleted: : Default is `false`. Indicates whether the monitor has been marked for deletion.
        :param pulumi.Input[_builtins.str] name: : The name of the monitor. Defaults to an empty string if not provided.
        :param pulumi.Input[_builtins.str] sensors: : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        :param pulumi.Input[_builtins.str] sinks: : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        :param pulumi.Input[_builtins.str] sinks_options: : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        :param pulumi.Input[_builtins.str] type: : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        :param pulumi.Input[_builtins.str] variables: : Additional settings required for specific monitor types.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _MonitorState.__new__(_MonitorState)

        __props__.__dict__["active"] = active
        __props__.__dict__["is_deleted"] = is_deleted
        __props__.__dict__["name"] = name
        __props__.__dict__["sensors"] = sensors
        __props__.__dict__["sinks"] = sinks
        __props__.__dict__["sinks_options"] = sinks_options
        __props__.__dict__["type"] = type
        __props__.__dict__["variables"] = variables
        return Monitor(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[_builtins.bool]:
        """
        : Indicates whether the monitor is enabled.
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter(name="isDeleted")
    def is_deleted(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        : Default is `false`. Indicates whether the monitor has been marked for deletion.
        """
        return pulumi.get(self, "is_deleted")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        : The name of the monitor. Defaults to an empty string if not provided.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def sensors(self) -> pulumi.Output[_builtins.str]:
        """
        : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
        """
        return pulumi.get(self, "sensors")

    @_builtins.property
    @pulumi.getter
    def sinks(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
        """
        return pulumi.get(self, "sinks")

    @_builtins.property
    @pulumi.getter(name="sinksOptions")
    def sinks_options(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
        """
        return pulumi.get(self, "sinks_options")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        : Additional settings required for specific monitor types.
        """
        return pulumi.get(self, "variables")

