# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyRoleAttachmentArgs', 'PolicyRoleAttachment']

@pulumi.input_type
class PolicyRoleAttachmentArgs:
    def __init__(__self__, *,
                 policies: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 role: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a PolicyRoleAttachment resource.
        """
        pulumi.set(__self__, "policies", policies)
        pulumi.set(__self__, "role", role)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def policies(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        return pulumi.get(self, "policies")

    @policies.setter
    def policies(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "policies", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _PolicyRoleAttachmentState:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policies: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering PolicyRoleAttachment resources.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policies is not None:
            pulumi.set(__self__, "policies", policies)
        if role is not None:
            pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def policies(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "policies")

    @policies.setter
    def policies(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "policies", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role", value)


@pulumi.type_token("komodor:index/policyRoleAttachment:PolicyRoleAttachment")
class PolicyRoleAttachment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policies: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Creates a logical binding between a Komodor Role and a Komodor Policy

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        my_policy = komodor.Policy("my-policy",
            name="my-policy",
            statements=\"\"\"[{
          \\"actions\\": [
            \\"get:daemonset\\",
            \\"edit:cronjob\\",
            \\"delete:service\\",
            \\"edit:job\\"
          ],
          \\"resources\\": [{
            \\"cluster\\": \\"kind-kind\\",
            \\"namespaces\\": [
              \\"default\\",
              \\"komodor\\"
            ]
          }]
        }]
        \"\"\")
        my_role = komodor.Role("my-role", name="my-role")
        my_attachement = komodor.PolicyRoleAttachment("my-attachement",
            name="test-attachement",
            policies=[my_policy.id],
            role=my_role.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PolicyRoleAttachmentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates a logical binding between a Komodor Role and a Komodor Policy

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        my_policy = komodor.Policy("my-policy",
            name="my-policy",
            statements=\"\"\"[{
          \\"actions\\": [
            \\"get:daemonset\\",
            \\"edit:cronjob\\",
            \\"delete:service\\",
            \\"edit:job\\"
          ],
          \\"resources\\": [{
            \\"cluster\\": \\"kind-kind\\",
            \\"namespaces\\": [
              \\"default\\",
              \\"komodor\\"
            ]
          }]
        }]
        \"\"\")
        my_role = komodor.Role("my-role", name="my-role")
        my_attachement = komodor.PolicyRoleAttachment("my-attachement",
            name="test-attachement",
            policies=[my_policy.id],
            role=my_role.id)
        ```


        :param str resource_name: The name of the resource.
        :param PolicyRoleAttachmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyRoleAttachmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policies: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyRoleAttachmentArgs.__new__(PolicyRoleAttachmentArgs)

            __props__.__dict__["name"] = name
            if policies is None and not opts.urn:
                raise TypeError("Missing required property 'policies'")
            __props__.__dict__["policies"] = policies
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
        super(PolicyRoleAttachment, __self__).__init__(
            'komodor:index/policyRoleAttachment:PolicyRoleAttachment',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            policies: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            role: pulumi.Input[Optional[_builtins.str]] = None) -> 'PolicyRoleAttachment':
        """
        Get an existing PolicyRoleAttachment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyRoleAttachmentState.__new__(_PolicyRoleAttachmentState)

        __props__.__dict__["name"] = name
        __props__.__dict__["policies"] = policies
        __props__.__dict__["role"] = role
        return PolicyRoleAttachment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def policies(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "policies")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "role")

