# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyArgs', 'Policy']

@pulumi.input_type
class PolicyArgs:
    def __init__(__self__, *,
                 statements: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Policy resource.
        """
        pulumi.set(__self__, "statements", statements)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def statements(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "statements")

    @statements.setter
    def statements(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "statements", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _PolicyState:
    def __init__(__self__, *,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 statements: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Policy resources.
        """
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if statements is not None:
            pulumi.set(__self__, "statements", statements)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def statements(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "statements")

    @statements.setter
    def statements(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "statements", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("komodor:index/policy:Policy")
class Policy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 statements: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Creates a Komodor RBAC Policy

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        my_policy = komodor.Policy("my-policy", statements=\"\"\"[{
          "actions": [
            "get:daemonset",
            "edit:cronjob",
            "delete:service",
            "edit:job"
          ],
          "resources": [{
            "cluster": "kind-kind",
            "namespaces": [
              "default",
              "komodor"
            ]
          }]
        }]

        \"\"\")
        ```

        ### Dyanmic Tags

        ```python
        import pulumi
        import pulumi_komodor as komodor

        # This example shows how to create a policy with dynamic tags.
        # Dynamic tags feature is not available by default.
        # When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
        komo_example_dynamic_tags_policy = komodor.Policy("komo-example-dynamic-tags-policy",
            type="dynamic_tag",
            tags={
                "team": "super-heroes",
            },
            statements=\"\"\"[{
          "actions": [
            "view:all"
          ],
          "resources": []
        }]
        \"\"\")
        ```

        ### Wildcard Namespace

        ```python
        import pulumi
        import pulumi_komodor as komodor

        komo_example_wildcard_policy = komodor.Policy("komo-example-wildcard-policy",
            statements=\"\"\"[{
          "actions": [
            "view:all"
          ],
          "resources": [{
            "cluster": "komo-example-cluster",
            "namespacePattern": "prod-*"
          }]
        }]

        \"\"\",
            type="wildcard")
        ```

        ### With Action

        ```python
        import pulumi
        import pulumi_komodor as komodor

        komo_example_pod_viewer = komodor.Action("komo-example-pod-viewer",
            action="pod-viewer",
            description="View pods",
            ruleset=\"\"\"[
          {
            "apiGroups": [
              "apps"
            ],
            "resources": [
              "pods"
            ],
            "verbs": [
              "get",
              "list"
            ]
          }
        ]

        \"\"\")
        komo_example_policy = komodor.Policy("komo-example-policy", statements=komo_example_pod_viewer.action.apply(lambda action: f\"\"\"[{{
          "actions": [
            "{action}"
          ],
          "resources": [{{
            "cluster": "komo-example-cluster",
            "namespaces": [
              "default",
              "kube-system"
            ]
          }}]
        }}]

        \"\"\"))
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates a Komodor RBAC Policy

        ## Example Usage

        ```python
        import pulumi
        import pulumi_komodor as komodor

        my_policy = komodor.Policy("my-policy", statements=\"\"\"[{
          "actions": [
            "get:daemonset",
            "edit:cronjob",
            "delete:service",
            "edit:job"
          ],
          "resources": [{
            "cluster": "kind-kind",
            "namespaces": [
              "default",
              "komodor"
            ]
          }]
        }]

        \"\"\")
        ```

        ### Dyanmic Tags

        ```python
        import pulumi
        import pulumi_komodor as komodor

        # This example shows how to create a policy with dynamic tags.
        # Dynamic tags feature is not available by default.
        # When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
        komo_example_dynamic_tags_policy = komodor.Policy("komo-example-dynamic-tags-policy",
            type="dynamic_tag",
            tags={
                "team": "super-heroes",
            },
            statements=\"\"\"[{
          "actions": [
            "view:all"
          ],
          "resources": []
        }]
        \"\"\")
        ```

        ### Wildcard Namespace

        ```python
        import pulumi
        import pulumi_komodor as komodor

        komo_example_wildcard_policy = komodor.Policy("komo-example-wildcard-policy",
            statements=\"\"\"[{
          "actions": [
            "view:all"
          ],
          "resources": [{
            "cluster": "komo-example-cluster",
            "namespacePattern": "prod-*"
          }]
        }]

        \"\"\",
            type="wildcard")
        ```

        ### With Action

        ```python
        import pulumi
        import pulumi_komodor as komodor

        komo_example_pod_viewer = komodor.Action("komo-example-pod-viewer",
            action="pod-viewer",
            description="View pods",
            ruleset=\"\"\"[
          {
            "apiGroups": [
              "apps"
            ],
            "resources": [
              "pods"
            ],
            "verbs": [
              "get",
              "list"
            ]
          }
        ]

        \"\"\")
        komo_example_policy = komodor.Policy("komo-example-policy", statements=komo_example_pod_viewer.action.apply(lambda action: f\"\"\"[{{
          "actions": [
            "{action}"
          ],
          "resources": [{{
            "cluster": "komo-example-cluster",
            "namespaces": [
              "default",
              "kube-system"
            ]
          }}]
        }}]

        \"\"\"))
        ```


        :param str resource_name: The name of the resource.
        :param PolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 statements: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyArgs.__new__(PolicyArgs)

            __props__.__dict__["name"] = name
            if statements is None and not opts.urn:
                raise TypeError("Missing required property 'statements'")
            __props__.__dict__["statements"] = statements
            __props__.__dict__["tags"] = tags
            __props__.__dict__["type"] = type
            __props__.__dict__["created_at"] = None
            __props__.__dict__["updated_at"] = None
        super(Policy, __self__).__init__(
            'komodor:index/policy:Policy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            statements: pulumi.Input[Optional[_builtins.str]] = None,
            tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'Policy':
        """
        Get an existing Policy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyState.__new__(_PolicyState)

        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["name"] = name
        __props__.__dict__["statements"] = statements
        __props__.__dict__["tags"] = tags
        __props__.__dict__["type"] = type
        __props__.__dict__["updated_at"] = updated_at
        return Policy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def statements(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "statements")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "updated_at")

