// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates a new Komodor RBAC action
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const komo_example_pod_viewer = new komodor.Action("komo-example-pod-viewer", {
 *     action: "pod-viewer",
 *     description: "View pods",
 *     ruleset: `[
 *   {
 *     "apiGroups": [
 *       "apps"
 *     ],
 *     "resources": [
 *       "pods"
 *     ],
 *     "verbs": [
 *       "get",
 *       "list"
 *     ]
 *   }
 * ]
 *
 * `,
 * });
 * const komo_example_policy = new komodor.Policy("komo-example-policy", {statements: pulumi.interpolate`[{
 *   "actions": [
 *     "${komo_example_pod_viewer.action}"
 *   ],
 *   "resources": [{
 *     "cluster": "komo-example-cluster",
 *     "namespaces": [
 *       "default",
 *       "kube-system"
 *     ]
 *   }]
 * }]
 *
 * `});
 * ```
 */
export class Action extends pulumi.CustomResource {
    /**
     * Get an existing Action resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ActionState, opts?: pulumi.CustomResourceOptions): Action {
        return new Action(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'komodor:index/action:Action';

    /**
     * Returns true if the given object is an instance of Action.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Action {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Action.__pulumiType;
    }

    declare public readonly action: pulumi.Output<string>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly ruleset: pulumi.Output<string>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Action resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ActionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ActionArgs | ActionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ActionState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["ruleset"] = state?.ruleset;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as ActionArgs | undefined;
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.ruleset === undefined && !opts.urn) {
                throw new Error("Missing required property 'ruleset'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["description"] = args?.description;
            resourceInputs["ruleset"] = args?.ruleset;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Action.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Action resources.
 */
export interface ActionState {
    action?: pulumi.Input<string | undefined>;
    createdAt?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    ruleset?: pulumi.Input<string | undefined>;
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Action resource.
 */
export interface ActionArgs {
    action: pulumi.Input<string>;
    description: pulumi.Input<string>;
    ruleset: pulumi.Input<string>;
}
