// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves an existing Komodor Kubernetes cluster integration by name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const dataK8sCluster = komodor.getKubernetes({
 *     clusterName: "my-cluster",
 * });
 * ```
 */
export function getKubernetes(args: GetKubernetesArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("komodor:index/getKubernetes:getKubernetes", {
        "clusterName": args.clusterName,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubernetes.
 */
export interface GetKubernetesArgs {
    /**
     * The name of the cluster; must be unique to a Komodor account
     */
    clusterName: string;
}

/**
 * A collection of values returned by getKubernetes.
 */
export interface GetKubernetesResult {
    /**
     * The name of the cluster; must be unique to a Komodor account
     */
    readonly clusterName: string;
    /**
     * The id and api key of the cluster integration
     */
    readonly id: string;
}
/**
 * Retrieves an existing Komodor Kubernetes cluster integration by name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const dataK8sCluster = komodor.getKubernetes({
 *     clusterName: "my-cluster",
 * });
 * ```
 */
export function getKubernetesOutput(args: GetKubernetesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("komodor:index/getKubernetes:getKubernetes", {
        "clusterName": args.clusterName,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubernetes.
 */
export interface GetKubernetesOutputArgs {
    /**
     * The name of the cluster; must be unique to a Komodor account
     */
    clusterName: pulumi.Input<string>;
}
