// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves an existing Komodor Policy by name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const dataK8sCluster = komodor.getPolicy({
 *     name: "my-policy",
 * });
 * ```
 */
export function getPolicy(args: GetPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("komodor:index/getPolicy:getPolicy", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyArgs {
    name: string;
}

/**
 * A collection of values returned by getPolicy.
 */
export interface GetPolicyResult {
    /**
     * The date and time of when the Policy was created
     */
    readonly createdAt: string;
    /**
     * The id of the policy
     */
    readonly id: string;
    readonly name: string;
    /**
     * The policy's statements
     */
    readonly statements: string;
    /**
     * The date and time of when the Policy was last updated
     */
    readonly updatedAt: string;
}
/**
 * Retrieves an existing Komodor Policy by name
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const dataK8sCluster = komodor.getPolicy({
 *     name: "my-policy",
 * });
 * ```
 */
export function getPolicyOutput(args: GetPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("komodor:index/getPolicy:getPolicy", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyOutputArgs {
    name: pulumi.Input<string>;
}
