// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates a new **Komodor monitor** to observe, detect, and analyze failures across your infrastructure. This resource allows you to define the parameters for monitoring specific components in your Kubernetes clusters and other infrastructure.
 *
 * ***
 *
 * ## Example Usage
 *
 * ### Deployment Monitor
 *
 * ### Valid Configurations:
 * - **Valid Sinks**: `slack`, `teams`, `webhook`
 * - **Valid notifyOn Options**:
 *   - `"Failure"`
 *   - `"Successful"`
 *   - `"All"`
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const example_deploy_monitor = new komodor.Monitor("example-deploy-monitor", {
 *     name: "example-deploy-monitor",
 *     type: "deploy",
 *     active: true,
 *     sensors: `[{
 *   \\"cluster\\": \\"kind-kind\\",
 *   \\"exclude\\": {
 *     \\"namespaces\\": [\\"komodor\\"]
 *   },
 *   \\"namespaces\\": [\\"default\\"]
 * }]
 * `,
 *     sinks: `{
 *   \\"slack\\": [\\"deployment-alerts\\"],
 *   \\"teams\\": [\\"Platform-Team\\"]
 * }
 * `,
 *     sinksOptions: `{
 *   \\"notifyOn\\": [\\"Failure\\", \\"Successful\\"]
 * }
 * `,
 * });
 * ```
 *
 * ***
 *
 * ### Availability Monitor
 *
 * ### Valid Configurations:
 * - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
 * - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
 * - **Valid Categories for variables.categories**:
 *   - `"Creating/Initializing"`
 *   - `"Scheduling"`
 *   - `"Container Creation"`
 *   - `"NonZeroExitCode"`
 *   - `"Unhealthy - failed probes"`
 *   - `"OOMKilled"`
 *   - `"BackOff"`
 *   - `"Infrastructure"`
 *   - `"Image"`
 *   - `"Volume/Secret/ConfigMap"`
 *   - `"Pod Termination"`
 *   - `"Completed"`
 *   - `"Other"`
 * - **Valid notifyOn Options**: `["*"]`
 *   - `["*"]` (all categories)
 *   - Or any one of the following:
 *     - `"Creating/Initializing"`
 *     - `"Scheduling"`
 *     - `"Container Creation"`
 *     - `"NonZeroExitCode"`
 *     - `"Unhealthy - failed probes"`
 *     - `"OOMKilled"`
 *     - `"BackOff"`
 *     - `"Infrastructure"`
 *     - `"Image"`
 *     - `"Volume/Secret/ConfigMap"`
 *     - `"Pod Termination"`
 *     - `"Completed"`
 *     - `"Other"`
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const example_availability_monitor = new komodor.Monitor("example-availability-monitor", {
 *     name: "example-availability-monitor",
 *     type: "availability",
 *     active: true,
 *     sensors: `[{
 *   \\"cluster\\": \\"kind-kind\\",
 *   \\"exclude\\": {
 *     \\"services\\": [\\"default/excluded-service\\"]
 *   },
 *   \\"services\\": [\\"default/important-service\\"],
 *   \\"condition\\": \\"and\\",
 *   \\"namespaces\\": [\\"default\\"]
 * }]
 * `,
 *     sinks: `{
 *   \\"slack\\": [\\"availability-alerts\\"],
 *   \\"teams\\": [\\"SRE-Team\\"]
 * }
 * `,
 *     variables: `{
 *   \\"categories\\": [\\"Creating/Initializing\\", \\"Unhealthy - failed probes\\"],
 *   \\"duration\\": 30,
 *   \\"minAvailable\\": \\"100%\\"
 * }
 * `,
 *     sinksOptions: `{
 *   \\"notifyOn\\": [\\"*\\"]
 * }
 * `,
 * });
 * ```
 *
 * ***
 *
 * ### Node Monitor
 *
 * ### Valid Configurations:
 * - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
 * - **Valid Duration**: Must be an integer between **5** and **600** (inclusive).
 * - **Valid NodeCreationThreshold: Should be in the format of `"3m"` (3 minutes) or `"5s"` (5 seconds).
 * - **Valid Variables**:
 *   - `duration`: Required
 *   - `nodeCreationThreshold`: Required
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const example_node_monitor = new komodor.Monitor("example-node-monitor", {
 *     name: "example-node-monitor",
 *     type: "node",
 *     active: true,
 *     sensors: `[{
 *   \\"cluster\\": \\"kind-kind\\"
 * }]
 * `,
 *     sinks: `{
 *   \\"slack\\": [\\"node-alerts\\"]
 * }
 * `,
 *     variables: `{
 *   \\"duration\\": 60,
 *   \\"nodeCreationThreshold\\": \\"10m\\"
 * }
 * `,
 * });
 * ```
 *
 * ***
 *
 * ### Workflow Monitor
 *
 * ### Valid Configurations:
 * - **Valid Sinks**: `slack`, `teams`, `opsgenie`, `pagerduty`, `webhook`
 * - **Valid notifyOn Options**: None (not applicable for workflows)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const example_workflow_monitor = new komodor.Monitor("example-workflow-monitor", {
 *     name: "example-workflow-monitor",
 *     type: "workflow",
 *     active: true,
 *     sensors: `[{
 *   \\"cluster\\": \\"kind-kind\\",
 *   \\"namespaces\\": [\\"workflow-namespace\\"]
 * }]
 * `,
 *     sinks: `{
 *   \\"slack\\": [\\"workflow-alerts\\"],
 *   \\"webhook\\": [\\"webhook-url\\"]
 * }
 * `,
 * });
 * ```
 *
 * ***
 */
export class Monitor extends pulumi.CustomResource {
    /**
     * Get an existing Monitor resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MonitorState, opts?: pulumi.CustomResourceOptions): Monitor {
        return new Monitor(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'komodor:index/monitor:Monitor';

    /**
     * Returns true if the given object is an instance of Monitor.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Monitor {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Monitor.__pulumiType;
    }

    /**
     * : Indicates whether the monitor is enabled.
     */
    declare public readonly active: pulumi.Output<boolean>;
    /**
     * : Default is `false`. Indicates whether the monitor has been marked for deletion.
     */
    declare public readonly isDeleted: pulumi.Output<boolean | undefined>;
    /**
     * : The name of the monitor. Defaults to an empty string if not provided.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
     */
    declare public readonly sensors: pulumi.Output<string>;
    /**
     * : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
     */
    declare public readonly sinks: pulumi.Output<string | undefined>;
    /**
     * : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
     */
    declare public readonly sinksOptions: pulumi.Output<string | undefined>;
    /**
     * : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * : Additional settings required for specific monitor types.
     */
    declare public readonly variables: pulumi.Output<string | undefined>;

    /**
     * Create a Monitor resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MonitorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MonitorArgs | MonitorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MonitorState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["isDeleted"] = state?.isDeleted;
            resourceInputs["name"] = state?.name;
            resourceInputs["sensors"] = state?.sensors;
            resourceInputs["sinks"] = state?.sinks;
            resourceInputs["sinksOptions"] = state?.sinksOptions;
            resourceInputs["type"] = state?.type;
            resourceInputs["variables"] = state?.variables;
        } else {
            const args = argsOrState as MonitorArgs | undefined;
            if (args?.active === undefined && !opts.urn) {
                throw new Error("Missing required property 'active'");
            }
            if (args?.sensors === undefined && !opts.urn) {
                throw new Error("Missing required property 'sensors'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["isDeleted"] = args?.isDeleted;
            resourceInputs["name"] = args?.name;
            resourceInputs["sensors"] = args?.sensors;
            resourceInputs["sinks"] = args?.sinks;
            resourceInputs["sinksOptions"] = args?.sinksOptions;
            resourceInputs["type"] = args?.type;
            resourceInputs["variables"] = args?.variables;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Monitor.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Monitor resources.
 */
export interface MonitorState {
    /**
     * : Indicates whether the monitor is enabled.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * : Default is `false`. Indicates whether the monitor has been marked for deletion.
     */
    isDeleted?: pulumi.Input<boolean | undefined>;
    /**
     * : The name of the monitor. Defaults to an empty string if not provided.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
     */
    sensors?: pulumi.Input<string | undefined>;
    /**
     * : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
     */
    sinks?: pulumi.Input<string | undefined>;
    /**
     * : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
     */
    sinksOptions?: pulumi.Input<string | undefined>;
    /**
     * : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * : Additional settings required for specific monitor types.
     */
    variables?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Monitor resource.
 */
export interface MonitorArgs {
    /**
     * : Indicates whether the monitor is enabled.
     */
    active: pulumi.Input<boolean>;
    /**
     * : Default is `false`. Indicates whether the monitor has been marked for deletion.
     */
    isDeleted?: pulumi.Input<boolean | undefined>;
    /**
     * : The name of the monitor. Defaults to an empty string if not provided.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * : Defines the scope of monitoring (e.g., cluster, namespaces, services, etc.).
     */
    sensors: pulumi.Input<string>;
    /**
     * : Defines notification channels for the monitor, such as Slack, Teams, PagerDuty, Opsgenie, or Webhook.
     */
    sinks?: pulumi.Input<string | undefined>;
    /**
     * : Specifies additional notification settings like notifyOn. Valid values depend on the monitor type.
     */
    sinksOptions?: pulumi.Input<string | undefined>;
    /**
     * : The monitor type. Must be one of: `availability`, `node`, `PVC`, `job`, `cronJob`, `deploy`, or `workflow`.
     */
    type: pulumi.Input<string>;
    /**
     * : Additional settings required for specific monitor types.
     */
    variables?: pulumi.Input<string | undefined>;
}
