// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates a Komodor RBAC Policy
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const my_policy = new komodor.Policy("my-policy", {
 *     name: "my-policy",
 *     statements: `[{
 *   \\"actions\\": [
 *     \\"get:daemonset\\",
 *     \\"edit:cronjob\\",
 *     \\"delete:service\\",
 *     \\"edit:job\\"
 *   ],
 *   \\"resources\\": [{
 *     \\"cluster\\": \\"kind-kind\\",
 *     \\"namespaces\\": [
 *       \\"default\\",
 *       \\"komodor\\"
 *     ]
 *   }]
 * }]
 * `,
 * });
 * ```
 *
 * ### Dyanmic Tags
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * // This example shows how to create a policy with dynamic tags.
 * // Dynamic tags feature is not available by default.
 * // When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
 * const komo_example_dynamic_tags_policy = new komodor.Policy("komo-example-dynamic-tags-policy", {
 *     name: "komo-example-dynamic-tags-policy",
 *     type: "dynamic_tag",
 *     tags: {
 *         team: "super-heroes",
 *     },
 *     statements: `[{
 *   \\"actions\\": [
 *     \\"view:all\\"
 *   ],
 *   \\"resources\\": []
 * }]
 * `,
 * });
 * ```
 *
 * ### Wildcard Namespace
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * // This example shows how to create a policy with a wildcard namespace pattern.
 * // wildcard policy type is not available by default.
 * // When the feature is disabled, applying this policy will fail with error: `400 Bad Request`
 * const komo_example_wildcard_policy = new komodor.Policy("komo-example-wildcard-policy", {
 *     name: "komo-example-wildcard-policy",
 *     type: "wildcard",
 *     statements: `[{
 *   \\"actions\\": [
 *     \\"view:all\\"
 *   ],
 *   \\"resources\\": [{
 *     \\"cluster\\": \\"komo-example-cluster\\",
 *     \\"namespacePattern\\": \\"prod-*\\"
 *   }]
 * }]
 * `,
 * });
 * ```
 *
 * ### With komodor.Action
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const komo_example_pod_viewer = new komodor.Action("komo-example-pod-viewer", {
 *     action: "pod-viewer",
 *     description: "View pods",
 *     ruleset: `[
 *   {
 *     \\"apiGroups\\": [
 *       \\"apps\\"
 *     ],
 *     \\"resources\\": [
 *       \\"pods\\"
 *     ],
 *     \\"verbs\\": [
 *       \\"get\\",
 *       \\"list\\"
 *     ]
 *   }
 * ]
 * `,
 * });
 * const komo_example_policy = new komodor.Policy("komo-example-policy", {
 *     name: "komo-example-policy",
 *     statements: pulumi.interpolate`[{
 *   \"actions\": [
 *     \"${komo_example_pod_viewer.action}\"
 *   ],
 *   \"resources\": [{
 *     \"cluster\": \"komo-example-cluster\",
 *     \"namespaces\": [
 *       \"default\",
 *       \"kube-system\"
 *     ]
 *   }]
 * }]
 * `,
 * });
 * ```
 */
export class Policy extends pulumi.CustomResource {
    /**
     * Get an existing Policy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyState, opts?: pulumi.CustomResourceOptions): Policy {
        return new Policy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'komodor:index/policy:Policy';

    /**
     * Returns true if the given object is an instance of Policy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Policy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Policy.__pulumiType;
    }

    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly statements: pulumi.Output<string>;
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    declare public readonly type: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Policy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyArgs | PolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["statements"] = state?.statements;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as PolicyArgs | undefined;
            if (args?.statements === undefined && !opts.urn) {
                throw new Error("Missing required property 'statements'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["statements"] = args?.statements;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Policy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Policy resources.
 */
export interface PolicyState {
    createdAt?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    statements?: pulumi.Input<string | undefined>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    type?: pulumi.Input<string | undefined>;
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Policy resource.
 */
export interface PolicyArgs {
    name?: pulumi.Input<string | undefined>;
    statements: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    type?: pulumi.Input<string | undefined>;
}
