// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates a logical binding between a Komodor Role and a Komodor Policy
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as komodor from "@pulumi/komodor";
 *
 * const my_policy = new komodor.Policy("my-policy", {statements: `[{
 *   "actions": [
 *     "get:daemonset",
 *     "edit:cronjob",
 *     "delete:service",
 *     "edit:job"
 *   ],
 *   "resources": [{
 *     "cluster": "kind-kind",
 *     "namespaces": [
 *       "default",
 *       "komodor"
 *     ]
 *   }]
 * }]
 * `});
 * const my_role = new komodor.Role("my-role", {});
 * const my_attachement = new komodor.PolicyRoleAttachment("my-attachement", {
 *     policies: [my_policy.id],
 *     role: my_role.id,
 * });
 * ```
 */
export class PolicyRoleAttachment extends pulumi.CustomResource {
    /**
     * Get an existing PolicyRoleAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyRoleAttachmentState, opts?: pulumi.CustomResourceOptions): PolicyRoleAttachment {
        return new PolicyRoleAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'komodor:index/policyRoleAttachment:PolicyRoleAttachment';

    /**
     * Returns true if the given object is an instance of PolicyRoleAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyRoleAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyRoleAttachment.__pulumiType;
    }

    declare public readonly name: pulumi.Output<string>;
    declare public readonly policies: pulumi.Output<string[]>;
    declare public readonly role: pulumi.Output<string>;

    /**
     * Create a PolicyRoleAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyRoleAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyRoleAttachmentArgs | PolicyRoleAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyRoleAttachmentState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["policies"] = state?.policies;
            resourceInputs["role"] = state?.role;
        } else {
            const args = argsOrState as PolicyRoleAttachmentArgs | undefined;
            if (args?.policies === undefined && !opts.urn) {
                throw new Error("Missing required property 'policies'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["policies"] = args?.policies;
            resourceInputs["role"] = args?.role;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyRoleAttachment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PolicyRoleAttachment resources.
 */
export interface PolicyRoleAttachmentState {
    name?: pulumi.Input<string | undefined>;
    policies?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    role?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a PolicyRoleAttachment resource.
 */
export interface PolicyRoleAttachmentArgs {
    name?: pulumi.Input<string | undefined>;
    policies: pulumi.Input<pulumi.Input<string>[]>;
    role: pulumi.Input<string>;
}
